name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpstan@v2

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
        composer-args:
          - ''
        include:
          - php-version: 7.1
            composer-args: '--prefer-lowest'

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          ini-values: zend.assertions=1

      - name: Install dependencies with Composer
        uses: php-actions/composer@v5
        with:
          args: ${{ matrix.dependencies }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=clover.xml

      - name: Upload coverage file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.php-version }}-${{ matrix.composer-args }}
          path: clover.xml


  coveralls-upload:
    name: Upload coverage to Coveralls
    runs-on: ubuntu-latest
    needs:
      - phpunit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Download coverage files
        uses: actions/download-artifact@v2
        with:
          path: build/logs

      - name: Install php-coveralls
        run: composer global require php-coveralls/php-coveralls

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php-coveralls --coverage_clover=build/logs/*/clover.xml -v
